### ISSUE TITLE
Object can only be in a single Group

### ISSUE THREAD

**Issue by 5axes** [5axes/FreeCAD-GDT#2]
Issue with Annotation Plane  .. As soon as I try to open a Datum Reference I have this message.

`14:43:18  Traceback (most recent call last):
14:43:18    File "C:\Users\----\AppData\Roaming\FreeCAD\Mod\GDT\.\GDT.py", line 1606, in createObject
14:43:18      makeDatumSystem(datumNAme, obj, None, None)
14:43:18    File "C:\Users\----\AppData\Roaming\FreeCAD\Mod\GDT\.\GDT.py", line 989, in makeDatumSystem
14:43:18      group.addObject(obj)
14:43:18  RuntimeError: {'sclassname': 'class Base::RuntimeError', 'sErrMsg': 'Object can only be in a single Group', 'sfile': '', 'iline': 0, 'sfunction': '', 'swhat': 'Object can only be in a single Group', 'btranslatable': False, 'breported': False}`

**Comment by 5axes** [comment]
I understood a little bit better the origin of the problem but for the moment I can't solve the problem. I cheated by using a try: to avoid having the error but it is still there. From what I could understand between the time when the WB was written and the current version the management of hierarchies has changed and I think that when the author had written his code this kind of problem did not exist.  So to be continued
