### ISSUE TITLE
Error Datum Feature in Annotation

### ISSUE THREAD

**Issue by 5axes** [5axes/FreeCAD-GDT#5]
Trying to Add A Datum Feature to an Annotation. 

Get again this message : **_Object can only be in a single Group_**

`18:10:23  Traceback (most recent call last):
18:10:23    File "C:\Users\----\AppData\Roaming\FreeCAD\Mod\GDT\inventory.py", line 94, in <lambda>
18:10:23      buttonModify.clicked.connect(lambda obj = obj, data = self.data: self.modifyFunc(obj, data))
18:10:23    File "C:\Users\---\AppData\Roaming\FreeCAD\Mod\GDT\inventory.py", line 137, in modifyFunc
18:10:23      data.annotation.addObject(obj)
18:10:23  RuntimeError: {'sclassname': 'class Base::RuntimeError', 'sErrMsg': 'Object can only be in a single Group', 'sfile': '', 'iline': 0, 'sfunction': '', 'swhat': 'Object can only be in a single Group', 'btranslatable': False, 'breported': False}`

**Comment by 5axes** [comment]
`                 
                annotationObj.removeObject(obj)
                annotationObj.DF = None
                
                data.annotation.addObject(obj)
                data.annotation.DF = obj
               
                remove = True
`
